services:
  # mongodb:
  #   image: mongo:7.0.12
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: mfesR00tPass

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.1
    labels:
      - "traefik.http.routers.keycloak.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.keycloak.middlewares=keycloak-stripprefix"
      - "traefik.http.middlewares.keycloak-stripprefix.stripprefix.prefixes=/auth"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HOSTNAME: http://localhost:8000/auth
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
    command: start-dev
    ports:
      - "9090:9000" 



  backend:
    build: ./backend
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  frontend:
    build: ./frontend
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    environment:
      HTTP_PORT: 8080
      FORMS_API: /api/forms

  reverse-proxy:
    image: traefik:v3.0.1
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "8000:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
